analytics: {}
color:
  brandColors:
    - '#333333'
    - '#A3A3A3'
    - '#D4D4D4'
    - '#545454'
    - '#797979'
  brandStrength: 0.10679345834068954
  lightness: 0.5148683632723987
  rhythmicContrast: 0.7583142328076065
  saturation: 0.9923356045037508
cta: {}
layout_spectrum: 0.414473
name: Savage Bartender
opengraph: {}
purpose: []
typography_spectrum: 0.711348
